### ISSUE TITLE
link_to_day_action sends to wrong date

### ISSUE THREAD

**Issue by slowcommotion** [elevation/event_calendar#10]
If you use the link_to_day_action property, it will send to the wrong date if you click on a day link that is not in the current month.

For example, if I am currently looking at January of 2010 and I click on the day link for December 31st 2009, it will not send me to the correct day.  Instead of ~day/2009/12/31 it will send to ~day/2010/1/31.

Not sure if there is a workaround since I am a noob to rails.   Any help would be appreciated.

Thanks for sharing the calendar.

**Comment by slowcommotion** [comment]
Got around this by changing the day_link function to also pass in the date month and year...

~\vendor\plugins\elevation-event_calendar-e080c87\lib\event_calendar\calendar_helper.rb

def day_link(text, date, day_action)
      link_to(text, params.merge(:action => day_action, :year => date.year, :month => date.month, :day => date.day), :class => 'ec-day-link')
    end

**Comment by jeffschuil** [comment]
Closed by 2345ab6b10c99bd4b53beab9e30cafee42dac505. Minor bug fix. When using the link_to_day_action option, it would send the wrong date when clicking on a day link not in the current month.
