### ISSUE TITLE
Year mode view

### ISSUE THREAD

**Issue by sobrinho** [elevation/event_calendar#13]
Hi,

I need to show all months of a specific year on my application. In this case, the navigation should be by year and not by month.

Is this possible?

**Comment by rubytastic** [comment]
Would love to know also..

**Comment by neophiliac** [comment]
Another vote for this one; I'd be happy with 6 months, though a year would be nice. I'll probably fake it with table_builder for now, but I'd prefer to use one calendar system underlying multiple views (1 month, 2 months, 6-12 months).

**Comment by paramveer** [comment]
Another vote! - I need to show 1-2 weeks, not an entire month to save on real-estate (plus my app is like that)

**Comment by vesuvius** [comment]
Another vote!
It will be very helpful if the navigation could be year by year.

**Comment by sobrinho** [comment]
Closing since we moved to another solution.
