### ISSUE TITLE
Event model name change is not reflected in links

### ISSUE THREAD

**Issue by ghost** [elevation/event_calendar#16]
I'm using a custom event model name, and I'm having trouble getting the event strip links to change their path. They still link to "/events/" even though I have "projects" and not "events". I tried changing line 239 of calendar_helper.rb but it has no effect. Where is this being set? Thanks in advance, G

**Comment by ghost** [comment]
P.S. I also edited helper.rb without success.

**Comment by jeffschuil** [comment]
The generator uses helper.rb as a template for creating a file in app/helpers. (The default name is calendar_helper.rb.) You should find the link for events within the event_calendar helper method.

The purpose of that generated file is just to provide some helper code to get you started. Modify away. :)

**Comment by ghost** [comment]
Thanks, I found the link.
