### ISSUE TITLE
Disappearing events when :first_day_of_week > 0

### ISSUE THREAD

**Issue by serek** [elevation/event_calendar#2]
When I try to change the value of :first_day_of_week bigger than 0 events are starting to disappear.

I have used it to show calendar for my Project model only which has: start_at, end_at and in project.rb:
has_event_calendar

**Comment by elevation** [comment]
Sorry it took awhile to get to, but this should be fixed. The option needed to be passed to the model as well (at least in the current implementation). I added this note in the README:

If you want to change the first day of the week from the default of Sunday (0), then set the new value in an instance variable and pass it to event_strips_for_month (in the controller), and to the event calendar options (in the helper/view).

Controller:
@first_day_of_week = 1
@event_strips = Event.event_strips_for_month(@shown_month, @first_day_of_week)

Helper/View calendar options:
:first_day_of_week => @first_day_of_week

**Comment by jsolid** [comment]
I found out that this will work if you're using event_strips_for_month().  It doesn't work on Event.create_event_strips() if :first_day_of_week > 0.

**Comment by elevation** [comment]
You need to pass the first day of week to the get_start_and_end_dates method. Something like this:

```
@first_day_of_week = 1
start_d, end_d = Event.get_start_and_end_dates(@shown_month, @first_day_of_week)
@events = Event.events_for_date_range(start_d, end_d)
@event_strips = Event.create_event_strips(start_d, end_d, @events)
```
