### ISSUE TITLE
Routes in Rails 3

### ISSUE THREAD

**Issue by jlousky** [elevation/event_calendar#28]
Hello, 
What is the proper routes syntax to use event_calendar in Rails 3 ?

The following is not working for me. I am getting this error below:
ActionController::RoutingError (No route matches "/calendar"):

Here's my routes code:

match '/calendar/:year/:month' => 'calendar#index', :as => :calendar ,  :requirements => {:year => /d{4}/, :month => /d{1,2}/}

Thanks, 

Jeremie

**Comment by jeffschuil** [comment]
I think you need the parenthesis making year/month optional. This is in the generator, but I'll add it to the README.

match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

**Comment by jlousky** [comment]
This worked. 

Thanks!
