### ISSUE TITLE
Undefined method `last_month'  - Calendar Helper

### ISSUE THREAD

**Issue by jlousky** [elevation/event_calendar#29]
Hi Jeff,

Thanks for the routes help. That worked...Now I have another error.

Error:

ActionView::Template::Error (undefined method `last_month' for Wed, 01 Dec 2010:Date):

Here's my calendar helper. (using Rails 3). When I comment out the  :previous_month_text, it works but otherwise it gives me the error above.

  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :event_height => 16 ,
      :day_names_height => 20,
      :event_padding_top => 0,
      :first_day_of_week => @first_day_of_week ,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.last_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

Thanks

**Comment by jeffschuil** [comment]
In Rails 3, you'll want to use prev_month, instead of last_month. This was also in the Rails 3 generator, but I'll make another note in the README.

**Comment by jlousky** [comment]
Thank you very much.

Great Job!

**Comment by jeffschuil** [comment]
Your welcome! Glad I could help.
