### ISSUE TITLE
:first_day_of_week causes problem

### ISSUE THREAD

**Issue by inprogs** [elevation/event_calendar#33]
when changed form 0 to 1 it doesn't show any event

I discovered that around line 202 in calendar_helper there is:

```
    if dates[0] == day.to_date
```

and that requirement is not met so i changed code at line 195

```
    day = first_day_of_week + index  
```

to
        day = first_day_of_week + index - options[:first_day_of_week]

It starts render events BUT not in appropriate columns. (moved by 1 to right)

I don't know how to fix it because I don't have any idea how the freaky strip method works in this code :-)

regards
Piotr Mąsior

**Comment by inprogs** [comment]
I solved it by correcting postions in array by 1

```
def correct_event_positions(event_strips)
new_event_strips = Array.new
new_strip = Array.new
event_strips.each do |strip|
  strip.each_with_index do |row,index|
    unless index == 0
      new_strip[index-1] = row
    end
  end
  new_event_strips << new_strip
  new_strip = Array.new
end
new_event_strips
end
#and in  event_calendar_opts
:event_strips => correct_event_positions(@event_strips),
```

**Comment by jeffschuil** [comment]
Glad you got it working.

I just tried setting first_day_of_week as outlined in the notes, and it appears to be working. Perhaps you had another option set, that I don't, and they are conflicting...

Just out of curiosity, did you pass in a first day of week parameter to the helper AND controller? Thanks.

As stated in the notes:

If you want to change the first day of the week from the default of Sunday (0), then set the new value in an instance variable and pass it to event_strips_for_month (in the controller), and to the event calendar options (in the helper/view).

Controller:
    @first_day_of_week = 1
    @event_strips = Event.event_strips_for_month(@shown_month, @first_day_of_week)

Helper/View calendar options:
    :first_day_of_week => @first_day_of_week
