### ISSUE TITLE
Missing backslashes in route RegEx

### ISSUE THREAD

**Issue by jaredcwhite** [elevation/event_calendar#39]
This is the Rails 2.x version. I was having problems with my routes after installing the plugin, and finally I tracked it down to missing backslashes in the requirements for the route. The generator created this:

map.calendar '/calendar/:year/:month', :controller => 'calendar', :action => 'index', :requirements => {:year => /d{4}/, :month => /d{1,2}/}, :year => nil, :month => nil

But it really should be this:

map.calendar '/calendar/:year/:month', :controller => 'calendar', :action => 'index', :requirements => {:year => /\d{4}/, :month => /\d{1,2}/}, :year => nil, :month => nil

Hope that helps! --Jared

**Comment by jeffschuil** [comment]
Fix the route that&#39;s generated for Rails 2. Closed by 50389f7b2b0f52a998d70624dff7f06a8cd2fbef.

**Comment by jaredcwhite** [comment]
Awesome! Glad to see it get updated so quickly!

**Comment by jeffschuil** [comment]
Yeah, it was a good catch. I'm kinda surprised someone hadn't brought this up sooner. Thanks for the help.
