### ISSUE TITLE
Doesn't show all events

### ISSUE THREAD

**Issue by johnnny** [elevation/event_calendar#5]
Hi,

I'm not sure if it's a specific bug with my application, but the events for the upcoming month don't fully show up on the current month. For instance if the events are on the 27,28,29,30,1,2,3 dates. The events show up correctly for all the dates except the 3rd (On a Saturday). The events on the 1st and 2nd show up fine. I'm not sure if it is supposed to be like this.

Thanks.

**Comment by elevation** [comment]
It was another timezone bug. Some events didn't show if they were on very last day of the calendar, in this case the 3rd of the upcoming month (Oct). The date stored in the db, in utc time zone, was the next date and thus not getting picked up by the find conditions. (Though it seems like ActiveRecord should've handled this...) Thanks for the find.
