### ISSUE TITLE
calendar_path Generates Bad Route

### ISSUE THREAD

**Issue by bensie** [elevation/event_calendar#6]
The named route for the calendar root generates a bad route:
map.calendar '/calendar/:year/:month', :controller => 'calendar', :action => 'index', :year => Time.zone.now.year, :month => Time.zone.now.month

calendar_path => /calendar//

**Comment by elevation** [comment]
I see what you mean. You can do this for now:

```
calendar_path(nil, nil)
```

**Comment by bensie** [comment]
In my app I'm dynamically generating root routes so that didn't work, I ended up adding an additional route:
map.calendar_root '/calendar', :controller => 'calendar'

Less than ideal, but works fine.

**Comment by ankopainting** [comment]
I did
    map.calendar 'calendar', :controller => 'calendar', :action => 'index', :year => Time.zone.now.year, :month => Time.zone.now.month
    map.connect  '/calendar/:year/:month', :controller => 'calendar', :action => 'index', :year => Time.zone.now.year, :month => Time.zone.now.month

I'm pretty sure it fixed it, but i don't have time to retest right now.

**Comment by KevinTriplett** [comment]
I did

```
map.admin_home '/admin/home/:action/:year/:month/:day', :controller => 'admin/home', :action => 'index',
  :requirements => {:year => /20\d\d/, :month => /[01]?\d/, :day => /[0-3]?\d/}, :day => nil, :month => nil, :year => nil
```

and in my controller I did

```
def calendar
  @month = (params[:month] || Time.zone.now.month).to_i
  @year = (params[:year] || Time.zone.now.year).to_i
  @shown_month = Date.civil(@year, @month)
  @event_strips = Event.event_strips_for_month(@shown_month)
end
```

Yet Another Way to do it. That way, you don't have to supply nils to the url helper.

**Comment by pjammer** [comment]
Would be nice to fix this if possible? i just passed calendar_path(Date.today) and got around it, but the nil's are good to know... however not having either would be awesome-er :-)  But may i be the 100th to say, THIS PLUGIN KICKS ASS, great job jeff.

**Comment by jamezilla** [comment]
This bug is fixed in my Rails 3 fork (github.com/jamezilla/event_calendar), but unfortunately requires Rails 3. It uses the new optional dynamic segments syntax.

**Comment by jeffschuil** [comment]
I ended up going with Kevin's method above (using a single route with :requirements and moving the date defaults to the controller). The generated route/controller has been updated for both Rails 2 & 3.
