### ISSUE TITLE
Can we make "start_at" & "end_at" dynamic?

### ISSUE THREAD

**Issue by rnhurt** [elevation/event_calendar#9]
I am using event_calendar on my own model (not Events) that doesn't contain a "start_at" or "end_at" field.  Actually, it contains quite a few date fields and I want to be able to pick and choose which ones show up on the calendar.  However, it looks like event_calendar is hardcoded to use these two fields.

Is there any way to make these field names selectable at runtime?  That way I could use my existing model and/or build several calendars each with different types of "events".

**Comment by KevinTriplett** [comment]
I'm in the same boat -- I'll take a look and see what I can propose. +1 for this feature.

Similar but not identical, I'd like the link for the event to pull up the edit resource url for my model. You may need this feature too?

**Comment by ryansmith3136** [comment]
I added this feature and sent a pull request. Here is my repo in the interim. 

http://github.com/ryandotsmith/event_calendar

**Comment by jeffschuil** [comment]
Ryan's work has been pulled into master. Thanks again for this feature.
